Repository andros21/rustracer, pull requests merged in 2022-05, with the labels that each got.

#32 fix(imagetracer): remove wrong offset and reverse vertical direction
  src/imagetracer.rs
Labels: bug

#33 add `demo` subcommand (preview of `render` subcommand)
  src/cli.rs
  src/color.rs
  src/error.rs
  src/hdrimage.rs
  src/main.rs
  src/misc.rs
  src/render.rs
  src/shape.rs
  src/world.rs
Labels: documentation, enhancement, rust

#37 feat(main): fail-fast for invalid/unsupported file format
  src/main.rs
  src/misc.rs
Labels: enhancement

#36 devel(makefile): helping development
  makefile
Labels: enhancement

#34 test: improve unit-tests and code coverage
  src/camera.rs
  src/normal.rs
  src/point.rs
  src/ray.rs
  src/shape.rs
  src/vector.rs
Labels: enhancement

#45 Implement path-tracing algorithm
  src/camera.rs
  src/cli.rs
  src/error.rs
  src/imagetracer.rs
  src/main.rs
  src/material.rs
  src/random.rs
  src/render.rs
  src/shape.rs
  src/world.rs
Labels: enhancement

#46 fix(rustracer): uniform use of `Self` as return type
  src/camera.rs
  src/hdrimage.rs
  src/imagetracer.rs
  src/normal.rs
  src/render.rs
  src/shape.rs
  src/transformation.rs
  src/vector.rs
Labels: enhancement
