Repository andros21/rustracer, pull requests merged in 2022-04, with the labels that each got.

#11 Geometry
  src/color.rs
  src/error.rs
  src/hdrimage.rs
  src/main.rs
  src/misc.rs
  src/normal.rs
  src/point.rs
  src/transformation.rs
  src/vector.rs
Labels: enhancement

#14 doc(rustracer): init documentation
  README.md
  src/cli.rs
  src/color.rs
  src/error.rs
  src/hdrimage.rs
  src/main.rs
  src/misc.rs
  src/normal.rs
  src/point.rs
  src/transformation.rs
  src/vector.rs
Labels: documentation

#15 fix(hdrimage): change `match` `for` order inside `read_pfm_image`
  src/hdrimage.rs
Labels: enhancement

#18 feat(test): little improvement in line code coverage
  src/hdrimage.rs
  src/normal.rs
  src/vector.rs
Labels: enhancement

#26 fix(camera): exchange `new` arguments in `PerspectiveCamera`
  src/camera.rs
Labels: bug
